version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      # anonymous volume node_modules 
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      # for hot-reloading  
      - CHOKIDAR_USEPOLLING=true
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    image: api
    depends_on:
      - cache
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
    links:
      - cache
    volumes:
      - ./server:/app
      - '/app/node_modules'
volumes:
  cache:
    driver: local
